from pathlib import Path
import json,uuid
exec((Path(__file__).resolve().parent/'verify-runtime.py').read_text().split('\ntry:\n current=')[0])
r={'status':'unconfirmed','operatingWrites':False,'externalCalls':0,'principal':'service_role','judgment':'synthetic DTO only; no model/provider invocation','cases':[]}
try:
 before=query(db,state_sql);sh=schema(db)
 # Exclusion must be due to fingerprint, not exhausted daily budget.
 policy="INSERT INTO pipeline_control.restaurant_review_policy(singleton,version,enabled,operator_id,batch_size,daily_limit) VALUES(true,7,true,"+L('actor')+",1,50);"
 for which in ['prior','applied']:
  fp="pipeline_control.restaurant_review_fingerprint(to_jsonb(t))" if which=='prior' else "repeat('b',64)";af="NULL" if which=='prior' else 'pipeline_control.restaurant_review_fingerprint(to_jsonb(t))'
  ledger="INSERT INTO pipeline_control.restaurant_review_runs(id,request_id,policy_version) VALUES('00000000-0000-4000-8000-000000000301',gen_random_uuid(),7);INSERT INTO pipeline_control.restaurant_review_items(run_id,restaurant_id,fingerprint,applied_fingerprint,decision,reason,state) SELECT '00000000-0000-4000-8000-000000000301',id,"+fp+','+af+",'recheck','fixture','applied' FROM public.restaurants t WHERE id="+lit(good['id'])+';'
  sql=auth_seed+insert(good)+policy+ledger+role+"DO $test$ DECLARE a jsonb;BEGIN a:=public.restaurant_review_automation_tick(gen_random_uuid());IF (a->>'scanned')::int<>0 OR (SELECT count(*) FROM pipeline_control.restaurant_review_items)<>1 OR (SELECT status FROM public.restaurants WHERE id="+lit(good['id'])+")<>'pending' THEN RAISE EXCEPTION 'REVIEW_FIX_FP_EXCLUSION';END IF;END $test$;ROLLBACK;"
  fixture(which+'_fingerprint_actual_tick_exclusion',sql)
 # One actual claim/complete creates a confirmed deferred judgment; only response DTO is synthetic.
 budget=dict(good);budget.update(id=str(uuid.uuid4()),trace_id=uuid.uuid4().hex,origin_name='budget fixture branch',approved_name='budget fixture branch',naver_name='budget fixture branch',youtube_link='https://www.youtube.com/watch?v=QRSTUVWXYZ0',status='approved',phone='02-999-1111')
 duplicate=dict(good);duplicate.update(id=str(uuid.uuid4()),trace_id=uuid.uuid4().hex,origin_name='duplicate fixture branch',approved_name='duplicate fixture branch',naver_name='duplicate fixture branch',youtube_link='https://www.youtube.com/watch?v=LMNOPQRSTUV',status='approved')
 evals=good['evaluation_results'].copy();evals['visit_authenticity']={'eval_value':1,'eval_basis':'synthetic revised completed evidence'}
 policy1=policy.replace(',1,50)',',1,1)')
 sql=auth_seed+insert(good)+insert(budget)+policy1+role+"DO $test$ DECLARE a jsonb;b jsonb;item jsonb;readback jsonb;token uuid:=gen_random_uuid();request uuid:=gen_random_uuid();judgment jsonb;current_fp text;BEGIN a:=public.restaurant_review_automation_tick(gen_random_uuid());IF (a->>'recheck')::int<>1 OR (a->>'scanned')::int<>1 THEN RAISE EXCEPTION 'REVIEW_FIX_INITIAL_ONE_BATCH';END IF;item:=public.restaurant_review_automation_worker('claim',NULL,token,'{}');IF item->>'id' IS NULL OR public.restaurant_review_automation_worker('claim',NULL,gen_random_uuid(),'{}') IS NOT NULL THEN RAISE EXCEPTION 'REVIEW_FIX_ONE_CLAIM';END IF;INSERT INTO pipeline_control.restaurant_review_items(run_id,restaurant_id,fingerprint,decision,reason,state,finished_at) SELECT run_id,"+lit(budget['id'])+",repeat('c',64),'approve','synthetic already consumed daily budget','applied',now() FROM pipeline_control.restaurant_review_items WHERE id=(item->>'id')::uuid;judgment:=jsonb_build_object('schemaVersion',1,'model','gemini-3.8-flash','modelVersion','gemini-3.8-flash','promptVersion','restaurant-review-v1','inputSha256',item#>>'{decisionContext,inputSha256}','promptSha256',repeat('a',64),'recommendation','approve','evidenceCodes',jsonb_build_array('visit_supported','identity_supported','review_grounded','category_supported','location_corroborated','source_consistent'));IF NOT pipeline_control.restaurant_review_gemini_valid(judgment,item#>>'{decisionContext,inputSha256}') THEN RAISE EXCEPTION 'REVIEW_FIX_JUDGMENT_SHAPE';END IF;a:=public.restaurant_review_automation_worker('complete',(item->>'id')::uuid,token,jsonb_build_object('evaluation_results',"+lit(json.dumps(evals))+"::jsonb,'gemini_decision',judgment));IF a#>>'{geminiDecision,outcome}'<>'deferred' OR NOT EXISTS(SELECT 1 FROM pipeline_control.restaurant_review_items WHERE id=(item->>'id')::uuid AND state='succeeded' AND reason='daily_limit' AND fingerprint<>applied_fingerprint) THEN RAISE EXCEPTION 'REVIEW_FIX_CONFIRMED_DEFERRED';END IF;SELECT pipeline_control.restaurant_review_fingerprint(to_jsonb(t)) INTO current_fp FROM public.restaurants t WHERE id="+lit(good['id'])+";"
 # Insert another real row while keeping the deferred row itself unchanged.
 sql+=insert(duplicate)+"IF pipeline_control.restaurant_review_fingerprint((SELECT to_jsonb(t) FROM public.restaurants t WHERE id="+lit(good['id'])+"))<>current_fp OR pipeline_control.restaurant_review_decision((SELECT to_jsonb(t) FROM public.restaurants t WHERE id="+lit(good['id'])+"))<>'hold:duplicate_requires_review' THEN RAISE EXCEPTION 'REVIEW_FIX_CHANGED_CLASSIFICATION_ONLY';END IF;a:=public.restaurant_review_automation_tick(request);IF (a->>'held')::int<>1 OR (a->>'scanned')::int<>1 OR (SELECT status FROM public.restaurants WHERE id="+lit(good['id'])+")<>'hold' THEN RAISE EXCEPTION 'REVIEW_FIX_CHANGED_DEFERRED_SKIPPED';END IF;readback:=public.restaurant_review_automation_worker('read',(item->>'id')::uuid,token,NULL);IF readback->>'state'<>'applied' OR readback->>'reason'<>'duplicate_requires_review' OR readback#>>'{geminiDecision,outcome}'<>'hold' THEN RAISE EXCEPTION 'REVIEW_FIX_DEFERRED_READBACK';END IF;b:=public.restaurant_review_automation_tick(request);IF a IS DISTINCT FROM b THEN RAISE EXCEPTION 'REVIEW_FIX_REQUEST_IDEMPOTENCY';END IF;b:=public.restaurant_review_automation_tick(gen_random_uuid());IF (b->>'scanned')::int<>0 OR public.restaurant_review_automation_worker('claim',NULL,gen_random_uuid(),'{}') IS NOT NULL THEN RAISE EXCEPTION 'REVIEW_FIX_DEFERRED_SECOND_BATCH';END IF;IF public.restaurant_review_automation_status()#>>'{judgmentEngine,maxCallsPerClaim}'<>'1' THEN RAISE EXCEPTION 'REVIEW_FIX_MODEL_CAP_CHANGED';END IF;END $test$;ROLLBACK;"
  # End SQL preserves completed item/capability and actual worker readback, with no provider call.
 fixture('confirmed_worker_deferred_then_classification_change',sql)
 assert query(db,state_sql)==before and schema(db)==sh;r.update(status='passed',fixtureRollbackExact=True,priorAndAppliedFingerprintExcluded=True,oneClaimOneBatch=True,confirmedDeferredReadbackAppliedHold=True,noPermanentSkip=True,maxCallsPerClaim=1)
except Exception as e:r['failure']={'state':e.state,'fixedCode':e.fixedCode,'object':e.object} if isinstance(e,SqlFailure) else {'kind':type(e).__name__}
finally:
 (out/'deferred-worker-runtime.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r))
 if r['status']!='passed':raise SystemExit(1)
