import type { Config } from "tailwindcss";

const ADMIN_EVALUATION_RESPONSIVE_DISPLAY_CLASSES = [
  // Admin evaluation table desktop mode depends on these display overrides.
  // Keep them safelisted so stale/incomplete dev CSS generation cannot leave
  // `hidden lg:block` / `hidden lg:table-cell` elements permanently hidden.
  "lg:block",
  "lg:flex",
  "lg:hidden",
  "lg:inline-flex",
  "lg:table-cell",
] as const;

const ADMIN_CONSOLE_RESPONSIVE_LAYOUT_CLASSES = [
  // The unified admin console is desktop-shell heavy. Safelist the shell
  // utilities that make the sidebar collapsible and keep icon-only mode
  // centered even when dev CSS is regenerated incrementally.
  "lg:border-r",
  "lg:border-y-0",
  "lg:grid",
  "lg:gap-0",
  "lg:h-11",
  "lg:h-[calc(100dvh_-_var(--app-header-height,0px))]",
  "lg:inline-flex",
  "lg:m-0",
  "lg:min-h-11",
  "lg:overflow-y-auto",
  "lg:px-0",
  "lg:px-1.5",
  "lg:place-items-center",
  "lg:sticky",
  "lg:top-0",
  "lg:w-0",
  "lg:w-11",
  "lg:w-14",
  "lg:w-56",
  // The KPI dashboard is intentionally dense on desktop. If these grid
  // utilities are dropped during dev CSS regeneration, the desktop dashboard
  // falls back to a one-column mobile layout and appears broken.
  "sm:col-span-2",
  "sm:grid-cols-2",
  "sm:grid-cols-5",
  "sm:grid-cols-6",
  "lg:col-span-2",
  "lg:col-span-3",
  "lg:col-span-4",
  "lg:col-span-5",
  "lg:flex-row",
  "lg:grid-cols-10",
  "lg:grid-cols-[minmax(0,1.05fr)_minmax(360px,0.95fr)]",
  "lg:grid-rows-[132px_minmax(0,1fr)_minmax(0,0.9fr)]",
  "lg:h-full",
  "lg:items-start",
  "lg:justify-between",
  "lg:min-h-0",
  "lg:overflow-hidden",
  "xl:grid-cols-3",
  "xl:grid-cols-4",
  "xl:grid-cols-[1.1fr_0.9fr]",
] as const;
const ADMIN_DASHBOARD_STYLE_CLASSES = [
  // The KPI dashboard builds several color/status classes from typed arrays.
  // In dev, incomplete Tailwind regeneration can omit those literal classes
  // from the route CSS chunk, leaving bars gray and badges unstyled.
  "font-sans",
  // Production route CSS must include the same dense KPI utilities that the
  // dev JIT emits from AdminConsoleOverview. Keep these explicit so Vercel
  // builds cannot drop placement and font-weight classes that change parity.
  "font-black",
  "font-extrabold",
  "gap-0",
  "flex-nowrap",
  "justify-end",
  "md:justify-end",
  "md:p-4",
  "md:border-y-0",
  "overflow-visible",
  "overflow-y-visible",
  "px-0.5",
  "grid-cols-[5.5rem_minmax(0,1fr)_3rem]",
  "grid-rows-2",
  "grid-rows-[auto_minmax(0,1fr)_auto]",
  "grid-rows-[minmax(0,1fr)_auto]",
  "min-h-[132px]",
  "min-h-[190px]",
  "min-h-[220px]",
  "min-h-[230px]",
  "min-h-[280px]",
  "min-w-[8%]",
  "min-w-fit",
  "sm:max-w-none",
  "sm:min-w-fit",
  "sm:p-1.5",
  "sm:p-3.5",
  "text-[13px]",
  "text-[clamp(1.2rem,1.45vw,1.75rem)]",
  "tracking-[-0.035em]",
  "tracking-[0.01em]",
  "tracking-[0.04em]",
  "bg-border/70",
  "bg-muted-foreground/25",
  "bg-muted-foreground/28",
  "bg-muted-foreground/30",
  "bg-muted-foreground/35",
  "bg-muted-foreground/45",
  "bg-muted-foreground/55",
  "bg-muted/25",
  "bg-muted/35",
  "bg-muted/45",
  "bg-teal-50",
  "bg-teal-500/55",
  "bg-teal-500/75",
  "border-teal-500/25",
  "dark:bg-muted-foreground/35",
  "dark:bg-muted-foreground/50",
  "dark:bg-muted/20",
  "dark:bg-muted/35",
  "dark:bg-teal-400/55",
  "dark:bg-teal-400/75",
  "dark:bg-teal-950/35",
  "dark:border-teal-400/30",
  "dark:text-background",
  "dark:text-emerald-300",
  "md:block",
  "md:flex",
  "md:hidden",
  "md:flex-row",
  "md:flex-wrap",
  "md:items-start",
  "md:justify-between",
  "md:gap-1",
  "md:w-auto",
  "md:overflow-visible",
  "md:pb-0",
  "sm:inline",
  "bg-sky-50",
  "bg-sky-50/20",
  "bg-sky-500",
  "bg-teal-500",
  "bg-rose-50",
  "bg-rose-500",
  "bg-orange-50",
  "bg-amber-500",
  "bg-amber-600",
  "bg-violet-500",
  "text-white",
  "text-teal-700",
  "text-sky-700",
  "text-rose-700",
  "text-amber-700",
  "border-sky-500/25",
  "border-sky-500/35",
  "border-rose-500/25",
  "border-orange-500/25",
  "dark:bg-sky-400",
  "dark:bg-sky-500",
  "dark:bg-sky-950/35",
  "dark:bg-sky-950/20",
  "dark:bg-teal-400",
  "dark:bg-teal-500",
  "dark:bg-rose-400",
  "dark:bg-rose-500",
  "dark:bg-rose-950/35",
  "dark:bg-orange-950/35",
  "dark:bg-amber-400",
  "dark:bg-amber-500",
  "dark:bg-violet-400",
  "dark:bg-violet-500",
  "dark:text-white",
  "dark:text-teal-300",
  "dark:text-sky-300",
  "dark:text-rose-300",
  "dark:text-amber-300",
  "dark:border-sky-400/30",
  "dark:border-sky-400/45",
  "dark:border-rose-400/30",
  "dark:border-orange-400/30",
] as const;
const MOBILE_BOTTOM_NAV_CLASSES = [
  // Direct mobile routes render MobileBottomNav without the home CSS chunk.
  // Keep the reference bottom-nav typography and active-state utilities present on every route.
  "-z-10",
  "text-red-800",
  "fill-red-800/20",
  "scale-110",
  "text-foreground/65",
  "active:text-foreground",
  "text-[12px]",
  "font-medium",
  "font-semibold",
  "leading-none",
  "tracking-normal",
] as const;
const LEADERBOARD_RANK_ICON_CLASSES = [
  // Rank icons are created from a helper, so direct mobile route chunks must keep their color utilities.
  "text-yellow-500",
  "text-muted-foreground",
  "text-amber-600",
] as const;



const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    ...ADMIN_EVALUATION_RESPONSIVE_DISPLAY_CLASSES,
    ...ADMIN_CONSOLE_RESPONSIVE_LAYOUT_CLASSES,
    ...ADMIN_DASHBOARD_STYLE_CLASSES,
    ...MOBILE_BOTTOM_NAV_CLASSES,
    ...LEADERBOARD_RANK_ICON_CLASSES,
    // MyPage profile desktop matrix depends on display: contents + equal row tracks.
    // Keep these emitted when dev CSS is regenerated incrementally.
    "md:contents",
    "md:grid-cols-2",
    "md:grid-rows-2",
    "md:content-stretch",
  ],
  theme: {
    extend: {
      screens: {
        xs: "375px",
      },
      fontFamily: {
        sans: [
          "var(--font-sans)",
          '"Pretendard"',
          '"Apple SD Gothic Neo"',
          '"Malgun Gothic"',
          '"Segoe UI"',
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        display: [
          "var(--font-display, var(--font-display-fallback))",
          '"Noto Serif KR"',
          '"Apple SD Gothic Neo"',
          '"Malgun Gothic"',
          "ui-serif",
          "Georgia",
          "serif",
        ],
        serif: [
          "var(--font-display, var(--font-display-fallback))",
          '"Noto Serif KR"',
          '"Apple SD Gothic Neo"',
          '"Malgun Gothic"',
          "ui-serif",
          "Georgia",
          "serif",
        ],
        mono: [
          "var(--font-mono)",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-secondary": "var(--gradient-secondary)",
      },
      boxShadow: {
        primary: "var(--shadow-primary)",
        glow: "var(--shadow-glow)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(-10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
