#!/usr/bin/env python3
"""Local thumbnail provider that drives Codex CLI's built-in $imagegen path.

This wrapper is intentionally for local development only. It lets the Next.js
admin thumbnail generator call the same Codex CLI OAuth-backed image-generation
surface that a human can use from the terminal, without treating gpt-image-2 as
the Codex *agent* model.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any


TARGET_WIDTH = 1280
TARGET_HEIGHT = 720
DEFAULT_MODEL = "gpt-image-2"
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a YouTube thumbnail via Codex CLI $imagegen and emit provider JSON.",
    )
    parser.add_argument("--prompt-file", required=True, help="Prompt text generated by the app")
    parser.add_argument("--output", required=True, help="Target image output path")
    parser.add_argument("--json-output", required=True, help="Provider JSON output path")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="Requested image model label")
    parser.add_argument("--reference-manifest", help="JSON manifest of reference image paths")
    parser.add_argument("--codex-bin", default=os.environ.get("CODEX_IMAGEGEN_CODEX_BIN", "codex"))
    parser.add_argument(
        "--agent-model",
        default=os.environ.get("CODEX_IMAGEGEN_AGENT_MODEL"),
        help="Optional Codex agent model. Do not set this to gpt-image-2.",
    )
    return parser.parse_args()


def die(message: str, code: int = 1) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(code)


def load_references(manifest_path: str | None) -> list[Path]:
    if not manifest_path:
        return []
    path = Path(manifest_path)
    if not path.exists():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    if not isinstance(payload, list):
        return []
    refs: list[Path] = []
    for item in payload:
        if not isinstance(item, dict):
            continue
        candidate = item.get("path")
        if isinstance(candidate, str) and candidate:
            ref = Path(candidate)
            if ref.exists() and ref.suffix.lower() in IMAGE_SUFFIXES:
                refs.append(ref)
    return refs[:8]


def newest_generated_image_since(started_at: float) -> Path | None:
    codex_home = Path(os.environ.get("CODEX_HOME", str(Path.home() / ".codex")))
    roots = [
        codex_home / "generated_images",
        codex_home,
    ]
    candidates: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES:
                try:
                    if path.stat().st_mtime >= started_at - 5:
                        candidates.append(path)
                except OSError:
                    continue
    if not candidates:
        return None
    return max(candidates, key=lambda path: path.stat().st_mtime)


def fit_image(src: Path, dst: Path) -> None:
    try:
        from PIL import Image, ImageOps
    except Exception as exc:  # pragma: no cover - runtime dependency guard
        die(f"Pillow is required to normalize Codex image output: {exc}")

    dst.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(src) as image:
        source = image.convert("RGB")
    fitted = ImageOps.fit(
        source,
        (TARGET_WIDTH, TARGET_HEIGHT),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )
    fitted.save(dst, format="PNG")


def condense_app_prompt(app_prompt: str) -> str:
    """Keep the child Codex imagegen prompt short enough to avoid agent drift."""
    interesting_prefixes = (
        "Content topic:",
        "Style preset:",
        "Editable headline placeholder",
        "Secondary editable caption",
        "Composition requirements:",
        "Host/person guidance:",
        "User image references:",
    )
    selected: list[str] = []
    for raw_line in app_prompt.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith(interesting_prefixes):
            selected.append(line)
    if not selected:
        selected.append(app_prompt.strip())

    condensed = "\n".join(selected)
    condensed = condensed[:1400]
    allow_specific_creator_host = "ALLOW_SPECIFIC_CREATOR_HOST" in app_prompt
    host_guidance = (
        "When Host/person guidance says ALLOW_SPECIFIC_CREATOR_HOST, include the requested Tzuyang/YouTube creator host as a respectful main mukbang reaction cutout or follow provided host/person references. Avoid defamatory, sexualized, deceptive, or private-life context.\n"
        if allow_specific_creator_host
        else "Include one clearly visible generic non-identifying host/reaction figure or silhouette when the brief mentions a host/reaction zone.\n"
    )
    return (
        "Create a 16:9 Korean YouTube mukbang or food-travel thumbnail base image.\n"
        "Use bright high-contrast food photography/collage styling with appetizing Korean dishes, warm restaurant lighting, and clear negative space for later text overlays.\n"
        f"{host_guidance}"
        "Do not include readable names, URLs, prices, brands, logos, watermarks, or UI chrome. Do not bake final typography into the image.\n"
        f"Brief:\n{condensed}"
    )


def build_codex_prompt(app_prompt: str, output_path: Path, model: str, references: list[Path]) -> str:
    reference_lines = "\n".join(f"- {path}" for path in references) or "- none"
    image_prompt = condense_app_prompt(app_prompt)
    model_note = (
        f"Use Codex CLI's built-in $imagegen image-generation tool. The desired image model label is {model}."
        if model == DEFAULT_MODEL
        else (
            f"Use Codex CLI's built-in $imagegen image-generation tool. The app requested image model label "
            f"{model!r}; if the built-in tool only exposes its default image model, use that default and report a warning."
        )
    )
    return f"""$imagegen
{model_note}

Task: generate exactly one raster image for a YouTube thumbnail draft.

Hard generation contract:
- Use the built-in image generation tool only.
- Do not run shell commands, do not call `codex exec -m gpt-image-2`, and do not create mock/SVG/placeholder output.
- Prefer a 16:9 landscape composition. The wrapper process will collect the generated image and normalize it to {TARGET_WIDTH}x{TARGET_HEIGHT} PNG at {output_path}; you do not need to save, crop, resize, verify, or copy files yourself.
- Respect the app prompt's Host/person guidance. If it says ALLOW_SPECIFIC_CREATOR_HOST, the main public creator/reference host may be visible; otherwise use a generic non-identifying host/reaction figure or silhouette.
- No logos, watermarks, visible UI chrome, readable real signage, names, prices, or contact text.
- Final reply should only state: generated.

Reference image files attached to this request:
{reference_lines}

Image prompt:
{image_prompt}
"""


def run_codex(args: argparse.Namespace, prompt: str, references: list[Path], answer_file: Path) -> subprocess.CompletedProcess[str]:
    repo_root = Path(os.environ.get("CODEX_IMAGEGEN_WORKDIR", str(Path(__file__).resolve().parents[1]))).resolve()
    command = [
        args.codex_bin,
        "exec",
        "--skip-git-repo-check",
        "--cd",
        str(repo_root),
        "--dangerously-bypass-approvals-and-sandbox",
        "--output-last-message",
        str(answer_file),
    ]
    if args.agent_model:
        if args.agent_model.startswith("gpt-image-"):
            die("CODEX_IMAGEGEN_AGENT_MODEL must be a Codex agent model, not an image model.")
        command.extend(["--model", args.agent_model])
    for ref in references:
        command.extend(["--image", str(ref)])
    command.append(prompt)
    print("Running:", " ".join(shlex.quote(part) for part in command[:6]), "...", file=sys.stderr)
    return subprocess.run(
        command,
        text=True,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=float(os.environ.get("CODEX_IMAGEGEN_TIMEOUT_SECONDS", "600")),
        check=False,
    )


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    args = parse_args()
    prompt_file = Path(args.prompt_file)
    output_path = Path(args.output).resolve()
    json_output_path = Path(args.json_output).resolve()
    if not prompt_file.exists():
        die(f"prompt file does not exist: {prompt_file}")

    app_prompt = prompt_file.read_text(encoding="utf-8")
    references = load_references(args.reference_manifest)
    started_at = time.time()
    with tempfile.TemporaryDirectory(prefix="codex-imagegen-thumbnail-") as tmp:
        answer_file = Path(tmp) / "codex-answer.txt"
        codex_prompt = build_codex_prompt(app_prompt, output_path, args.model, references)
        result = run_codex(args, codex_prompt, references, answer_file)

        if not output_path.exists():
            generated = newest_generated_image_since(started_at)
            if not generated:
                if result.returncode != 0:
                    write_json(
                        json_output_path,
                        {
                            "model": args.model,
                            "warnings": ["codex_cli_imagegen_failed"],
                            "stdout": result.stdout[-1200:],
                            "stderr": result.stderr[-1200:],
                        },
                    )
                    sys.stderr.write(result.stderr[-4000:])
                    return result.returncode or 1
                write_json(
                    json_output_path,
                    {
                        "model": args.model,
                        "warnings": ["codex_cli_imagegen_no_output_found"],
                        "stdout": result.stdout[-1200:],
                        "stderr": result.stderr[-1200:],
                    },
                )
                die("Codex imagegen completed but no generated image was found.")
            fit_image(generated, output_path)
        else:
            # Normalize even if Codex saved the file itself; the app expects 16:9 PNG output.
            fit_image(output_path, output_path)

        warnings = ["codex_cli_imagegen_oauth: generated via Codex CLI built-in $imagegen"]
        if result.returncode != 0:
            warnings.append("codex_cli_nonzero_after_image: collected generated image despite non-zero Codex exit")
        if args.model != DEFAULT_MODEL:
            warnings.append(f"requested_model_label: {args.model}")
        write_json(
            json_output_path,
            {
                "path": str(output_path),
                "mime": "image/png",
                "model": args.model,
                "warnings": warnings,
            },
        )
    print(json.dumps({"path": str(output_path), "mime": "image/png", "model": args.model}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
