#!/usr/bin/env python3
"""Local storyboard-panel provider backed by Codex CLI's built-in $imagegen.

This wrapper is local-development only. It is intentionally separate from the
YouTube thumbnail wrapper so storyboard prompts produce one storyboard panel
instead of thumbnail base art, while still using Codex CLI OAuth image
generation rather than API-key mocks.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any


TARGET_WIDTH = 1280
TARGET_HEIGHT = 720
DEFAULT_MODEL = "gpt-image-2"
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate one storyboard panel via Codex CLI $imagegen and emit provider JSON.",
    )
    parser.add_argument("--prompt-file", required=True, help="Prompt text generated by the app")
    parser.add_argument("--output", required=True, help="Target image output path")
    parser.add_argument("--json-output", required=True, help="Provider JSON output path")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="Requested image model label")
    parser.add_argument("--codex-bin", default=os.environ.get("CODEX_IMAGEGEN_CODEX_BIN", "codex"))
    parser.add_argument(
        "--agent-model",
        default=os.environ.get("CODEX_IMAGEGEN_AGENT_MODEL"),
        help="Optional Codex agent model. Do not set this to gpt-image-2.",
    )
    return parser.parse_args()


def die(message: str, code: int = 1) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(code)


def newest_generated_image_since(started_at: float) -> Path | None:
    codex_home = Path(os.environ.get("CODEX_HOME", str(Path.home() / ".codex")))
    roots = [
        codex_home / "generated_images",
        codex_home,
    ]
    candidates: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES:
                try:
                    if path.stat().st_mtime >= started_at - 5:
                        candidates.append(path)
                except OSError:
                    continue
    if not candidates:
        return None
    return max(candidates, key=lambda path: path.stat().st_mtime)


def fit_image(src: Path, dst: Path) -> None:
    try:
        from PIL import Image, ImageOps
    except Exception as exc:  # pragma: no cover - runtime dependency guard
        die(f"Pillow is required to normalize Codex image output: {exc}")

    dst.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(src) as image:
        source = image.convert("RGB")
    fitted = ImageOps.fit(
        source,
        (TARGET_WIDTH, TARGET_HEIGHT),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )
    fitted.save(dst, format="PNG")


def condense_app_prompt(app_prompt: str) -> str:
    selected: list[str] = []
    prefixes = (
        "Storyboard title:",
        "Overall logline:",
        "User brief:",
        "CUT ",
        "Visual direction:",
        "Operator intent:",
        "Caption idea",
        "Heatmap evidence mood:",
    )
    for raw_line in app_prompt.splitlines():
        line = raw_line.strip()
        if line and line.startswith(prefixes):
            selected.append(line)
    if not selected:
        selected.append(app_prompt.strip())
    return "\n".join(selected)[:1600]


def build_codex_prompt(app_prompt: str, output_path: Path, model: str) -> str:
    model_note = (
        f"Use Codex CLI's built-in $imagegen image-generation tool. The desired image model label is {model}."
        if model == DEFAULT_MODEL
        else (
            f"Use Codex CLI's built-in $imagegen image-generation tool. The app requested image model label "
            f"{model!r}; if the built-in tool only exposes its default image model, use that default and report a warning."
        )
    )
    return f"""$imagegen
{model_note}

Task: generate exactly one raster image for a storyboard panel.

Hard generation contract:
- Use the built-in image generation tool only.
- Do not run shell commands, do not call `codex exec -m gpt-image-2`, and do not create mock/SVG/placeholder output.
- Generate one 16:9 storyboard-panel image. The wrapper process will collect the generated image and normalize it to {TARGET_WIDTH}x{TARGET_HEIGHT} PNG at {output_path}; you do not need to save, crop, resize, verify, or copy files yourself.
- Hand-drawn storyboard sketch style with clean black pencil lines and subtle warm food-color accents.
- No readable text baked into the image, no logos, no watermarks, no UI chrome, no prices, no URLs, and no real-person likeness recreation.
- Final reply should only state: generated.

Image prompt:
{condense_app_prompt(app_prompt)}
"""


def run_codex(args: argparse.Namespace, prompt: str, answer_file: Path) -> subprocess.CompletedProcess[str]:
    repo_root = Path(os.environ.get("CODEX_IMAGEGEN_WORKDIR", str(Path(__file__).resolve().parents[1]))).resolve()
    agent_effort = os.environ.get("CODEX_IMAGEGEN_AGENT_EFFORT", "").strip()
    command = [
        args.codex_bin,
        "exec",
        "--skip-git-repo-check",
        "--cd",
        str(repo_root),
        "--dangerously-bypass-approvals-and-sandbox",
        "--output-last-message",
        str(answer_file),
    ]
    if args.agent_model:
        if args.agent_model.startswith("gpt-image-"):
            die("CODEX_IMAGEGEN_AGENT_MODEL must be a Codex agent model, not an image model.")
        command.extend(["--model", args.agent_model])
    if agent_effort:
        if agent_effort not in {"low", "medium", "high"}:
            die("CODEX_IMAGEGEN_AGENT_EFFORT must be one of: low, medium, high.")
        command.extend(["-c", f"model_reasoning_effort={agent_effort!r}"])
    command.append(prompt)
    print("Running:", " ".join(shlex.quote(part) for part in command[:6]), "...", file=sys.stderr)
    return subprocess.run(
        command,
        text=True,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=float(os.environ.get("CODEX_IMAGEGEN_TIMEOUT_SECONDS", "600")),
        check=False,
    )


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    args = parse_args()
    prompt_file = Path(args.prompt_file)
    output_path = Path(args.output).resolve()
    json_output_path = Path(args.json_output).resolve()
    if not prompt_file.exists():
        die(f"prompt file does not exist: {prompt_file}")

    app_prompt = prompt_file.read_text(encoding="utf-8")
    started_at = time.time()
    with tempfile.TemporaryDirectory(prefix="codex-imagegen-storyboard-") as tmp:
        answer_file = Path(tmp) / "codex-answer.txt"
        codex_prompt = build_codex_prompt(app_prompt, output_path, args.model)
        result = run_codex(args, codex_prompt, answer_file)

        if not output_path.exists():
            generated = newest_generated_image_since(started_at)
            if not generated:
                if result.returncode != 0:
                    write_json(
                        json_output_path,
                        {
                            "model": args.model,
                            "warnings": ["codex_cli_storyboard_imagegen_failed"],
                            "stdout": result.stdout[-1200:],
                            "stderr": result.stderr[-1200:],
                        },
                    )
                    sys.stderr.write(result.stderr[-4000:])
                    return result.returncode or 1
                write_json(
                    json_output_path,
                    {
                        "model": args.model,
                        "warnings": ["codex_cli_storyboard_imagegen_no_output_found"],
                        "stdout": result.stdout[-1200:],
                        "stderr": result.stderr[-1200:],
                    },
                )
                die("Codex imagegen completed but no generated storyboard image was found.")
            fit_image(generated, output_path)
        else:
            fit_image(output_path, output_path)

        warnings = ["codex_cli_imagegen_oauth: generated storyboard panel via Codex CLI built-in $imagegen"]
        if result.returncode != 0:
            warnings.append("codex_cli_nonzero_after_image: collected generated image despite non-zero Codex exit")
        if args.model != DEFAULT_MODEL:
            warnings.append(f"requested_model_label: {args.model}")
        write_json(
            json_output_path,
            {
                "path": str(output_path),
                "mime": "image/png",
                "model": args.model,
                "warnings": warnings,
            },
        )
    print(json.dumps({"path": str(output_path), "mime": "image/png", "model": args.model}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
