from pathlib import Path
import json
exec((Path(__file__).resolve().parent/'fixture-lib-lock.py').read_text())
db=json.loads((out/'lock-three-migration-replay.json').read_text())['database'];r={'status':'unconfirmed','operatingWrites':False,'principal':'service_role','externalCalls':0}
try:
 before=query(db,state_sql);sh=schema(db)
 sql=seed.replace('BEGIN;','BEGIN;INSERT INTO pipeline_control.admin_evaluation_catalog_revision(singleton,revision) VALUES(true,0);',1)+"INSERT INTO pipeline_control.restaurant_review_policy(singleton,version,enabled,operator_id,batch_size,daily_limit) VALUES(true,7,true,"+L('actor')+",50,50);SET LOCAL ROLE service_role;SELECT set_config('request.jwt.claims','{\"role\":\"service_role\"}',true);"
 sql+="DO $test$ DECLARE p jsonb;a jsonb;run uuid:=gen_random_uuid();q uuid:=gen_random_uuid();i uuid:=gen_random_uuid();token uuid:=gen_random_uuid();BEGIN INSERT INTO pipeline_control.restaurant_review_runs(id,request_id,policy_version) VALUES(run,gen_random_uuid(),7);INSERT INTO pipeline_control.restaurant_review_items(id,run_id,restaurant_id,fingerprint,decision,reason,state,worker_token,lease_until) VALUES(q,run,"+L('target')+",'fixture-queued','recheck','fixture','queued',NULL,NULL),(i,run,"+L('source')+",'fixture-running','recheck','fixture','running',token,now()+interval '1 hour');p:=public.restaurant_review_automation_manual("+L('actor')+",'preview-stop',NULL,NULL,NULL);IF (p->'queue'->>'queued')::int<>1 OR (p->'queue'->>'running')::int<>1 OR length(p->>'previewHash')<>32 THEN RAISE EXCEPTION 'REVIEW_FIX_QUEUE_PREVIEW';END IF;a:=public.restaurant_review_automation_manual("+L('actor')+",'stop',p->>'version',p->>'previewHash',NULL);IF (SELECT enabled FROM pipeline_control.restaurant_review_policy WHERE singleton) OR (SELECT count(*) FROM pipeline_control.restaurant_review_items WHERE id IN(q,i) AND state='cancelled' AND finished_at IS NOT NULL)<>2 OR (SELECT version FROM pipeline_control.restaurant_review_policy WHERE singleton)<>8 THEN RAISE EXCEPTION 'REVIEW_FIX_QUEUE_STOP';END IF;a:=public.restaurant_review_automation_worker('finish',i,token,'{}');IF a<>'{\"disabled\":true}' THEN RAISE EXCEPTION 'REVIEW_FIX_STOP_WORKER_APPLIED';END IF;a:=public.restaurant_review_automation_worker('read',i,token,NULL);IF a->>'state'<>'cancelled' THEN RAISE EXCEPTION 'REVIEW_FIX_STOP_READBACK';END IF;END $test$;ROLLBACK;"
 (out/'manual-stop-queued-running-fixture.sql').write_text(sql);run(db,sql);assert query(db,state_sql)==before and schema(db)==sh;r.update(status='passed',queuedCancelled=1,runningCancelled=1,policyDisabled=True,versionIncremented=True,lateWorkerFinishDisabled=True,workerReadbackCancelled=True,fixtureRollbackExact=True)
except Exception as e:r['failure']={'state':e.state,'fixedCode':e.fixedCode,'object':e.object} if isinstance(e,SqlFailure) else {'kind':type(e).__name__}
finally:
 (out/'manual-stop-queue-runtime.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r))
 if r['status']!='passed':raise SystemExit(1)
