import assert from 'node:assert/strict';
import {test} from 'node:test';
import {fixtureQuery} from './fixture-query-v3.mjs';
const rows=[{id:'a',name:'첫 식당',approved_name:'첫 식당',lat:37.5,lng:127,categories:['한식'],status:'approved',youtube_meta:null},{id:'b',name:'둘,째 식당',approved_name:'둘,째 식당',lat:38,lng:127,categories:['분식'],status:'approved',youtube_meta:null}];
const query=input=>fixtureQuery(rows,new URLSearchParams(input));
test('compact SELECT projection and alias',()=>{const result=query('select=id,name:approved_name,lat,lng');assert.deepEqual(result.data[0],{id:'a',name:'첫 식당',lat:37.5,lng:127});assert.equal(Object.hasOwn(result.data[0],'youtube_meta'),false);assert.equal(result.total,2);});
test('quoted name IN including comma',()=>{assert.deepEqual(fixtureQuery(rows,new URLSearchParams({approved_name:'in.("둘,째 식당")',select:'id,name:approved_name'})).data,[{id:'b',name:'둘,째 식당'}]);});
test('search and viewport subsets',()=>{assert.deepEqual(query('approved_name=ilike.%첫%').data.map(row=>row.id),['a']);assert.deepEqual(query('lat=gte.37&lat=lte.37.6&id=in.(a,b)').data.map(row=>row.id),['a']);});
test('array overlap versus contains',()=>{assert.equal(query('categories=ov.{한식,분식}').data.length,2);assert.equal(query('categories=cs.{한식,분식}').data.length,0);});
test('pagination and total',()=>{assert.deepEqual(query('order=id.desc&offset=1&limit=1&select=id'),{data:[{id:'a'}],total:2});});
test('unsupported predicate is explicit',()=>{assert.throws(()=>query('lat=unexpected.1'),/fixture_predicate_unsupported/);});
