// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fubnhgkdtabnkxfupchb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1Ym5oZ2tkdGFibmt4ZnVwY2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMDkwMzUsImV4cCI6MjA3NjU4NTAzNX0.sIsb0DphfD6KrSaybTYdd50pIm3L0n2s0pZLyMlL7DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});