// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fubnhgkdtabnkxfupchb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1Ym5oZ2tkdGFibmt4ZnVwY2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMDkwMzUsImV4cCI6MjA3NjU4NTAzNX0.sIsb0DphfD6KrSaybTYdd50pIm3L0n2s0pZLyMlL7DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web',
    },
  },
  // API 요청 타임아웃 설정
  db: {
    schema: 'public',
  },
  rest: {
    timeout: 10000, // 10초 타임아웃
  },
});

// 토큰 만료 감지 및 자동 재시도 로직
let isRefreshing = false;
let refreshPromise: Promise<any> | null = null;

supabase.auth.onAuthStateChange(async (event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('Token refreshed successfully');
  } else if (event === 'SIGNED_OUT') {
    console.log('User signed out');
  }
});

// 개선된 글로벌 API 요청 인터셉터 (새로고침 시 안정성 향상)
const originalFetch = globalThis.fetch;
globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
  try {
    const response = await originalFetch(input, init);

    // 401 에러 감지 시 토큰 갱신 시도 (새로고침 시 더 안전하게)
    if (response.status === 401 && !response.url?.includes('/auth/')) {
      if (!isRefreshing) {
        isRefreshing = true;
        refreshPromise = (async () => {
          try {
            console.log('Attempting to refresh token due to 401 error');
            const { data, error } = await supabase.auth.refreshSession();

            if (error) {
              console.error('Token refresh failed:', error);
              // 토큰 갱신 실패 시 세션 클리어 (강제 리로드하지 않음)
              await supabase.auth.signOut();
              return null;
            }

            if (data.session) {
              console.log('Token refreshed successfully');
              return data.session.access_token;
            }
            return null;
          } finally {
            isRefreshing = false;
            refreshPromise = null;
          }
        })();

        const newToken = await refreshPromise;
        if (newToken) {
          console.log('Retrying request with refreshed token');
          // 토큰 갱신 성공 시 원래 요청 재시도
          return originalFetch(input, {
            ...init,
            headers: {
              ...init?.headers,
              Authorization: `Bearer ${newToken}`,
            },
          });
        }
      } else if (refreshPromise) {
        // 이미 리프레시 중인 경우 대기
        const newToken = await refreshPromise;
        if (newToken) {
          return originalFetch(input, {
            ...init,
            headers: {
              ...init?.headers,
              Authorization: `Bearer ${newToken}`,
            },
          });
        }
      }
    }

    return response;
  } catch (error) {
    // 네트워크 에러인 경우 재시도하지 않음 (새로고침 시 안정성)
    console.error('Network error:', error);
    throw error;
  }
};