// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fubnhgkdtabnkxfupchb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1Ym5oZ2tkdGFibmt4ZnVwY2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwMDkwMzUsImV4cCI6MjA3NjU4NTAzNX0.sIsb0DphfD6KrSaybTYdd50pIm3L0n2s0pZLyMlL7DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web',
    },
  },
  // API 요청 타임아웃 설정
  db: {
    schema: 'public',
  },
  rest: {
    timeout: 10000, // 10초 타임아웃
  },
});

// 토큰 만료 감지 및 자동 재시도 로직
let isRefreshing = false;
let refreshPromise: Promise<any> | null = null;

supabase.auth.onAuthStateChange(async (event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('Token refreshed successfully');
  } else if (event === 'SIGNED_OUT') {
    console.log('User signed out');
  }
});

// 글로벌 API 요청 인터셉터
const originalFetch = globalThis.fetch;
globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
  try {
    const response = await originalFetch(input, init);

    // 401 에러 감지 시 토큰 갱신 시도
    if (response.status === 401) {
      if (!isRefreshing) {
        isRefreshing = true;
        try {
          console.log('Attempting to refresh token due to 401 error');
          const { data, error } = await supabase.auth.refreshSession();

          if (error) {
            console.error('Token refresh failed:', error);
            // 토큰 갱신 실패 시 로그아웃
            await supabase.auth.signOut();
            window.location.reload();
            return response;
          }

          if (data.session) {
            console.log('Token refreshed, retrying request');
            // 토큰 갱신 성공 시 원래 요청 재시도
            return originalFetch(input, {
              ...init,
              headers: {
                ...init?.headers,
                Authorization: `Bearer ${data.session.access_token}`,
              },
            });
          }
        } finally {
          isRefreshing = false;
        }
      }
    }

    return response;
  } catch (error) {
    console.error('Network error:', error);
    throw error;
  }
};